dependencies:
- name: jenkins-x-platform
  repository: https://storage.googleapis.com/chartmuseum.jenkins-x.io
- alias: jx-app-kuberhealthy
  condition: jx-app-kuberhealthy.enabled
  name: jx-app-kuberhealthy
  repository: https://storage.googleapis.com/chartmuseum.jenkins-x.io
  version: 0.0.2
- name: jx-app-replicator
  repository: https://storage.googleapis.com/chartmuseum.jenkins-x.io
  version: 1.0.14
- name: jx-tenant-service
  repository: https://storage.googleapis.com/chartmuseum.jenkins-x.io
  version: 0.0.256
- name: jxboot-resources
  repository: https://storage.googleapis.com/chartmuseum.jenkins-x.io
- name: jxui-arcalos
  repository: https://charts.cloudbees.com/cjxd/cloudbees
  version: 0.0.992
- alias: lighthouse
  condition: lighthouse.enabled
  name: lighthouse
  repository: https://storage.googleapis.com/chartmuseum.jenkins-x.io
- name: lighthouse-githubapp
  repository: https://storage.googleapis.com/chartmuseum.jenkins-x.io
  version: 0.0.165
- alias: prow
  condition: prow.enabled
  name: prow
  repository: https://storage.googleapis.com/chartmuseum.jenkins-x.io
- alias: tekton
  name: tekton
  repository: https://storage.googleapis.com/chartmuseum.jenkins-x.io
- name: oauth-proxy2
  repository: https://kubernetes-charts.storage.googleapis.com/
  version: 4.0.0
